export enum TYPES {
  HIDE_APP = 'HIDE_APP',
  SHOW_APP = 'SHOW_APP',
  SHOW_ONBOARDING = 'SHOW_ONBOARDING',
  FETCH_PROFILE_DATA = 'FETCH_PROFILE_DATA',
  FETCH_DATA_PROFILE_ATTEMPT = 'FETCH_DATA_PROFILE_ATTEMPT',
  FETCH_DATA_PROFILE_SUCCESS = 'FETCH_DATA_PROFILE_SUCCESS',
  FETCH_DATA_PROFILE_FAIL = 'FETCH_DATA_PROFILE_FAIL',
}
