export const NAVIGATION_ROUTES = {
  DRAWER_DASHBOARD: 'DRAWER_DASHBOARD',
  DRAWER_PROFILE: 'DRAWER_PROFILE',

  SCREEN_DASHBOARD: 'SCREEN_DASHBOARD',

  TAB_MAIN: 'TAB_MAIN',
  TAB_MOBILE: 'TAB_MOBILE',
  TAB_WEB: 'TAB_WEB',
};

export const NAVIGATION_TITLES = {
  [NAVIGATION_ROUTES.DRAWER_DASHBOARD]: 'Dashboard',
  [NAVIGATION_ROUTES.DRAWER_PROFILE]: 'Profile',
  [NAVIGATION_ROUTES.TAB_MAIN]: 'Main',
  [NAVIGATION_ROUTES.TAB_MOBILE]: 'Mobile',
  [NAVIGATION_ROUTES.TAB_WEB]: 'Web',
};
