export enum NAVIGATION_ROUTES {
  DRAWER_DASHBOARD = 'DRAWER_DASHBOARD',
  DRAWER_PROFILE = 'DRAWER_PROFILE',

  SCREEN_DASHBOARD = 'SCREEN_DASHBOARD',

  TAB_MAIN = 'TAB_MAIN',
  TAB_MOBILE ='TAB_MOBILE',
  TAB_WEB = 'TAB_WEB',
};

export enum NAVIGATION_TITLES {
  DRAWER_DASHBOARD = 'Dashboard',
  DRAWER_PROFILE = 'Profile',
  TAB_MAIN = 'Main',
  TAB_MOBILE = 'Mobile',
  TAB_WEB = 'Web',
};
