export const NAVIGATION_ROUTES = {
  DRAWER_DASHBOARD: 'DRAWER_DASHBOARD',
  DRAWER_PROFILE: 'DRAWER_PROFILE',

  SCREEN_DASHBOARD: 'SCREEN_DASHBOARD',

  TAB_MAIN: 'TAB_MAIN',
  TAB_MOBILE: 'TAB_MOBILE',
  TAB_WEB: 'TAB_WEB',
};
